### ISSUE TITLE
Exclude items with a itemGroupId

### ISSUE THREAD

**Issue by mattgrul** [klevultd/frontend-sdk#209]
I am running a pretty basic search with a searchTerm against Product Records. The products held in Klevu are a combination of the compound product and the variants. I am wanting the query to exclude all compound products from the result.

Yes, this could be done after the query by checking if itemGroupId exists however that would then throw the limit off say if I was expecting 10 products to return and 3 were excluded so this needs to be done on the query side.

Ideally I was hoping for something like this to exclude compound products but keep the variants but it does not work, if anyone can point me in the right direction?

```
export function getProducts(searchTerm) {
    return search(
        searchTerm,
        {
            id: 'search',
            typeOfRecords: [KlevuTypeOfRecord.Product],
            limit: 10,
            excludeIds: [{
                key: 'itemGroupId',
                value: '*'
            }]
        },
    )
}
````

**Comment by rallu** [comment]
Hello! Here is the full list of configurations for the searching and the documentation for it: https://docs.klevu.com/apis/smart-search-configurations

Only settings that effects results that I know are `groupBy` and `disableGrouping` in your case. 

Then there are backend settings that where we can change what is returned by the API. But for that you need to contact our support in here https://help.klevu.com/support/tickets/new

**Comment by jerrypena1** [comment]
hi @mattgrul 

Just incase the message from @rallu isn't what you are looking for, I believe a customANDQuery might work instead of excludeIds. 

```
export function getProducts(searchTerm) {
    return search(
        searchTerm,
        {
            id: 'search',
            typeOfRecords: [KlevuTypeOfRecord.Product],
            limit: 10,
            customANDQuery: '-(itemGroupId:*)'
        },
    )
}
```

The general idea is that customANDQuery becomes a filter based on the underlying data in addition to the term, typeOfRecords, etc. Adding the "-" at the beginning changes the query to prohibit the match, so it's like a logical NOT operator. If you remove the "-" at the beginning, then you end up with only products which have an itemGroupId. 

Under the hood, Klevu uses solr as the query language within the customANDQuery, so you might want to [checkout this link](https://solr.apache.org/guide/6_6/the-standard-query-parser.html) for other little tricks you can use for this setting parameter. 

Even if this is not exactly what you're looking for, I'm sure you can find something interesting to do with it :) Hope this is helpful.

**Comment by mattgrul** [comment]
@jerrypena1 Just got back around to this and works flawlessly, thank you so much :+1:
