### ISSUE TITLE
Analytics Events

### ISSUE THREAD

**Issue by mattgrul** [klevultd/frontend-sdk#220]
Two part query regarding Events:

In my live quick search bar at the top of every page I have an implementation like so, 

return search(
    searchTerm,
    {
        id: 'search',
        ...
    },
    sendSearchEvent()
);

This sends the data and I can see this on the "Live View" in the KMC however it seems to contradict this line here https://docs.klevu.com/headless-sdk/events-analytics - "Typically requests should be implemented to all KlevuFetch calls. Only exception is that when implementing "Quicksearch" bar (a search bar on top of page that shows results right away) it should not  send these events." But when adding sendSearchEvent() events gets sent on users keyup/down search?

The second part of the question is the difference between KlevuResultEvent.getSearchClickSendEvent and KlevuEvents.searchProductClick they both seems to achieve the same thing is there a correct time and place to use one or the other? E.g. what should be used in the live quick search bar when clicking a product vs maybe clicking a product on a full search results page?

**Comment by jerrypena1** [comment]
hi @mattgrul 

Regarding the quick search, I believe the recommendation is not to send those searches to KMC since the user hasn't "committed" to performing a search yet. Most quick search only display the first few results, no filters, etc., so by committed I mean that they have navigated to the search result page. There isn't anything technically wrong with logging your user's quick searches, but it might create more noise for the person going through the analytics. 

Regarding the second part I looked at the source code and KlevuEvents.searchProductClick is the low level function used by the click handler you get from getSearchClickSendEvent. The click handler just doesnt need as many parameters since its already tied to the search, so it's just more convenient to use the click handlers IMHO.
