### ISSUE TITLE
Filters applied for the category collection erases the filtering per category

### ISSUE THREAD

**Issue by tkarasovagomage** [klevultd/frontend-sdk#222]
Hello!
We're trying to implement our product catalog categories using Klevu on our Magento 2 PWA website. 
Once we fetch products that belong to a specific category and then apply a filter (for example, by color) on top of that, the previous rule that fetches products for a specific category erases and the color filter is applied to a whole catalog.

Example of the code we use to retrieve category-specific products:
const res = await KlevuFetch(
    klevuSearch(
        categoryName,
        {
            id: "categoryProductSearch",
            groupBy: 'id', // needed to have
            limit: itemsOnPage,
            sort: sorting,
            typeOfRecords: [KlevuTypeOfRecord.Product]
        },
        listFilters({
            rangeFilterSettings: [{
                key: "klevu_price",
                minMax: true
            }],
            filterManager: manager
        }),
        applyFilters([
            {
                key: "category",
                values: [categoryName], // e.g. "Water Systems"
                settings: {
                    singleSelect: true
                }
            }
        ]),
        applyFilterWithManager(manager)
        // ...modifiers
    )
)

And then we trigger the unique filter button that triggers **_manager.toggleOption(key, name)_** method, where 
key - option key, e.g. (color)
name - option value, e.g. [red]:

return (
    <button
        key={index}
        className={classes.item}
        onClick={() => {manager.toggleOption(key, name)}}
    >
        <span className={iconClassname}>
            <FontAwesomeIcon icon={['far', 'check']} className={classes.checked}/>
        </span>
        <span className={classes.name}>{name}</span>
        <span className={classes.counter}>({count})</span>
    </button>
)

And for now, it seems that this unique filter erases and overrides the previously applied category filter. Is there any chance it could be checked and/or fixed?

Regards,
Tanya.

**Comment by rallu** [comment]
Hey there! The problem is that applyFiltersWithManager overrides what you have set with applyFilters. You need to use just one of them. Either by modifying state of FilterManager before making the request and use applyFiltersWithManager or you take options and sliders from FilterManager and extend them with your own applyFilters query. 

But I think there is easier way of doing what you are trying to do. `categoryMerchandising` query function can take search term as option do the search in the category. But this requires merchandising tool to be enabled in the plan.
