### ISSUE TITLE
Not possible to use a custom method for the products filtering

### ISSUE THREAD

**Issue by tkarasovagomage** [klevultd/frontend-sdk#235]
Hello!
We're trying to adjust Klevu logic to add pagination and filter parameters to the URL, to have it like that:
 https://domain.com/categoryurl?page=1&on_sale%5Bfilter%5D=Yes&brand%5Bfilter%5D=Kinetico&brand%5Bfilter%5D=Whirlpool

We're trying to add the following data to be stored in hash and be used by Klevu manager:
import {FilterManager} from "@klevu/core";
​
export const useSetKlevuFilterFromUrl = () => {
    const currentUrl = window.location.href;
    const manager = new FilterManager();
​
    // Parse the current URL to extract the query parameters
    const url = new URL(currentUrl);
    const params = new URLSearchParams(url.search);
​
    // Get all query parameter keys that end with '[filter]'
    const filterParamKeys = Array.from(params.keys())
        .filter(key => key.endsWith('[filter]'));
​
    // Construct an array of objects representing the applied filters
    const appliedFiltersArr = filterParamKeys.map(key => {
        const filterKey = key.replace('[filter]', '');
        const filterValues = params.getAll(key);
​
        return {
            key: filterKey,
            values: filterValues
        };
    });
​
    // Remove repeating values in the appliedFiltersArr
    const uniqueFiltersArr = [];
    for (let filter of appliedFiltersArr) {
        if (!uniqueFiltersArr.some(f => f.key === filter.key)) {
            uniqueFiltersArr.push(filter);
        }
    }
​
    for (const option of uniqueFiltersArr) {
        const { key, values } = option;
        for (const value of values) {
            manager.toggleOption(key, value);
        }
    }
​
    return uniqueFiltersArr;
}

However, manager doesn't use the data and we cannot ask for the pre-filtered collection from Klevu.
As a reference, here is the object created from the URL with parameters:
[
    {
        "key": "on_sale",
        "values": [
            "Yes"
        ]
    },
    {
        "key": "brand",
        "values": [
            "Kinetico",
            "Whirlpool"
        ]
    },
    {
        "key": "klevu_price",
        "values": [
            "0",
            "7499"
        ]
    }
]

And here is the one returned from Klevu API once the filter is applied:
[
    {
        "key": "brand",
        "values": [
            "Kinetico",
            "Whirlpool Water"
        ],
        "settings": {
            "singleSelect": false
        }
    },
    {
        "key": "on_sale",
        "values": [
            "Yes"
        ],
        "settings": {
            "singleSelect": false
        }
    }
]

As far as we see, once the request is created to Klevu, there is an **applyFilterWithManager(manager)** method that is used by default to apply filters. We have tried to add our own method here **(applyFilterWithManager(appliedFiltersArrFromUrl?.length > 0 ? appliedFiltersArrFromUrl : manager )**,
But then the storefront crashed with the following error manager.toApplyFilters is not a function (where appliedFiltersArrFromUrl is the method in which code is shared at the beginning of the message).
Could you please provide a piece of advice here on how can we achieve what's needed?

**Comment by jerrypena1** [comment]
Hi @tkarasovagomage there is a way to preselect filters when you create a new FilterManager instance. I'm working on making an example for you, but one way is shown in the [test file for the FilterManager](https://github.com/klevultd/frontend-sdk/blob/master/packages/klevu-core/src/store/filterManager.test.ts). The FilterManager instance has a function called initFromListFilters which lets you pass in the filters. This way when you perform the search using the FilterManager instance it already has the right filters selected and performs the search so you get the correct filtered response.

**Comment by tkarasovagomage** [comment]
Hello, Juan!
We would wait for your response here since the example provided doesn't
work for us.

   1. We add the same filters list *const appliedFiltersArrFromUrl =
   useSetKlevuFilterFromUrl();*
   2. Then send the list to the manager
   *manager.initFromListFilters(appliedFiltersArrFromUrl);*
   3. The filters are not rendered on the page and we received an
   *undefined* response.

I hope that the example you'll create for us will suit us well.
Please let me know if I can provide you with some more information/details
here.

Regards,
--
[image: GoMage]
Tetiana Karasova

Project Manager | GoMage
38 093 904 2402 <+38+093+904+2402>
***@***.***
[image: https://www.linkedin.com/in/tetiana-karasova-855b1a179/]
<https://www.linkedin.com/in/tetiana-karasova-855b1a179/> [image:
https://en-gb.facebook.com/GoMage/] <https://en-gb.facebook.com/GoMage/>
<http://twitter.com/GoMagecom> <https://www.youtube.com/GoMage>

**Comment by jerrypena1** [comment]
Thank you for the feedback. I've been digging into the SDK code a bit more and took a closer look at your code. There are two things to keep in mind: 

1) you cannot pass an object instead of the FilterManager instance. There are functions that are being expected, so you must use the initFromListFilters function.  
2) The initFromListFilters  function is expecting a specific structure, so you cannot pass in the exact same type of object that  is used in the API request/response. Again, this is because the FilterManger instance has checks within its code to ensure that everything will function properly. 

That being said, it looks like the only things used inside of each object within the array passed into initFromListFilters are: the type, key, and options within each filter, then within the options array each object needs the value and selected. So this means that the other values, although required for the UI, are not actually used to make the request; which is what you are trying to do. 

So looking at your URL parameters, use the same key value as the label and add the type which is also required. Then for each option, use the same value as the name and add selected (true since you're only doing this for the selected filters) + count (count can be any number since the actual value used is what comes back after the request is made).

If you look at [this codesandbox](https://fhn5q9.csb.app/), you will notice that I am applying the same type of data that you have but I'm making up the label, name, and count values since they will be replaced when I get the response, so only the key, value and selected actually matter (plus the type for each option since it needs to know if its an option or slider type of filter). In your code it is very likely you know exactly which ones are sliders, so I'd build an array to check agains, and apply a KlevuFilterType.Slider if it is a slider (which needs different values by the way), otherwise it defaults to KlevuFilterType.Options.

**Comment by rallu** [comment]
There are new methods in FilterManager that make it easy to export and import URL parameters.
